base_url = "https://www.poemgreen.net"
title = "绿松石"
description = "个人诗藏集，存语段剔除与拼合"
author = "M1nTT"
default_language = "zh-CN"
compile_sass = true
minify_html = true

[markdown]
insert_anchor_links = "right"
bottom_footnotes = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[slugify]
paths = "on"
anchors = "on"

[extra]
email = "hi@poemgreen.net"
blog = "https://www.tongmingzhi.com"